[package]
name = "vimz"
version = "1.3.0"
edition = "2021"

[dependencies]
nova-scotia = "0.5.0"
nova-snark = "0.23.0"
pasta_curves = "0.5"
serde = "1.0"
serde_json = "1.0.85"
clap = "2.33"

[[bin]]
name = "vimz"
path = "src/main.rs"
