[package]
name = "vimz"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nova-scotia = "0.5.0"
# anyhow = "1.0.65"
# bellperson = { version = "0.25", default-features = false }
# byteorder = "1.4.3"
# ff = { version = "0.13", features = ["derive"]}
# hex-literal = "0.3.4"
# itertools = "0.9.0"
nova-snark = "0.23.0"
# num-bigint = { version = "0.4", features = ["serde", "rand"] }
# num-traits = "0.2.15"
pasta_curves = "0.5"
serde = "1.0"
serde_json = "1.0.85"
clap = "2.33"

[[bin]]
name = "vimz"
path = "src/main.rs"

